### ISSUE TITLE
Recent images not found

### ISSUE THREAD

**Issue by yogeek** [uzxmx/dockerhub-build-trigger#2]
Hi and thank you for this repository.

Some recent images (v1.18.6, v1.18.5 or v1.17.9 for example) are missing.
I guess these images it is because they are quite recent, right ?

How often is the Travis CI cron job launched please ?

**Comment by uzxmx** [comment]
@yogeek Sorry for the delay. 

Actually, the cron job is run weekly. You can check the status [here](https://travis-ci.org/github/uzxmx/dockerhub-build-trigger).

Thanks for the report, I just found the problem: because of the [strategy](https://github.com/uzxmx/dockerhub-build-trigger/blob/c3d80435528cf651906e89fcfe9353f835affe00/scripts/check_new_versions.sh#L65) that only fetches newer versions which are greater than the maximum version on the local, when the local maximum version is 1.20.0-alpha.0, any versions like v1.18.6, v1.18.5 and v1.19.x won't be fetched.

I just did a quickfix that specifies `-s` option to synchronize all versions that compares against the minimum version on the local. You can find the change [here](https://github.com/uzxmx/dockerhub-build-trigger/pull/3/commits/62a97cfe56c2210fa271dd3c7410e022405f43e2).

All the image builds have been triggered in dockerhub. After a while, you will see them.

**Comment by yogeek** [comment]
Nice, thank you !
